# Generated by Django 4.2.4 on 2023-08-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_pr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('under_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_pr.underservice')),
            ],
        ),
    ]
